name: build

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Cache packages when the branch is not update-dependencies or renovate/*
      - name: Resolve caching
        id: cache
        if: ${{ github.ref_name != 'update-dependencies' && !startsWith(github.ref_name, 'renovate/') }}
        run: echo "npm_cache=npm" >> $GITHUB_STATE

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: ${{ env.npm_cache }}

      # Install dependencies
      - run: npm ci

      # Build
      - run: npm run build 
        env:
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
